spring:
  profiles:
    active:
      - dev
---
server:
  port: 9100
spring:
  profiles: dev
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 9200
spring:
  profiles: test
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 9300
spring:
  profiles: prod
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/