spring:
  profiles:
    active:
      - dev
---
server:
  port: 8100
spring:
  profiles: dev
  application:
    name: welcome-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka
---
server:
  port: 8200
spring:
  profiles: test
  application:
    name: welcome-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9200/eureka
---
server:
  port: 8300
spring:
  profiles: prod
  application:
    name: welcome-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9300/eureka