spring:
  application:
    name: config-server
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: config-server
---
spring:
  profiles: test
  application:
    name: config-server-test
---
spring:
  profiles: prod
  application:
    name: config-server-prod